// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Compiler = require("../src/compiler/Compiler.res.js");

function compileFile(src, dest, backend) {
  var content = Fs.readFileSync(src, "utf8");
  var options = {
    debugAST: false,
    includeComments: false,
    backend: backend
  };
  var code = Compiler.compile(content, options, undefined);
  if (code.TAG === "Ok") {
    Fs.writeFileSync(dest, code._0, "utf8");
    console.log("✓ Success: Generated " + dest);
    return ;
  }
  console.log("✗ Error: " + code._0);
}

function generateDestPath(src, backend) {
  var baseName = src.endsWith(".res") ? src.slice(0, src.length - 4 | 0) : src;
  if (backend === "IC10") {
    return baseName + ".ic10";
  } else {
    return baseName + ".wat";
  }
}

function parseBackend(arg) {
  var match = arg.toLowerCase();
  switch (match) {
    case "ic10" :
        return "IC10";
    case "wasm" :
    case "wat" :
        return "WASM";
    default:
      return ;
  }
}

var match = process.argv[2];

var match$1 = process.argv[3];

if (match !== undefined) {
  if (match$1 !== undefined) {
    var backend = parseBackend(match$1);
    if (backend !== undefined) {
      var dest = generateDestPath(match, backend);
      console.log("Compiling: " + match + " -> " + dest + " (backend: " + match$1 + ")");
      compileFile(match, dest, backend);
    } else {
      console.log("Error: Unknown backend '" + match$1 + "'");
      console.log("Usage: node scripts/compile.res.js <source.res> [ic10|wasm]");
      console.log("  ic10 - Compile to IC10 assembly (.ic10)");
      console.log("  wasm - Compile to WebAssembly text format (.wat)");
    }
  } else {
    var dest$1 = generateDestPath(match, "IC10");
    console.log("Compiling: " + match + " -> " + dest$1 + " (backend: ic10)");
    compileFile(match, dest$1, "IC10");
  }
} else {
  console.log("Usage: node scripts/compile.res.js <source.res> [backend]");
  console.log("");
  console.log("Arguments:");
  console.log("  source.res - ReScript source file to compile");
  console.log("  backend    - Target backend (optional, default: ic10)");
  console.log("");
  console.log("Backends:");
  console.log("  ic10 - IC10 assembly language (default) -> .ic10");
  console.log("  wasm - WebAssembly text format         -> .wat");
  console.log("");
  console.log("Examples:");
  console.log("  node scripts/compile.res.js src/basic.res");
  console.log("  node scripts/compile.res.js src/basic.res ic10");
  console.log("  node scripts/compile.res.js src/basic.res wasm");
}

exports.compileFile = compileFile;
exports.generateDestPath = generateDestPath;
exports.parseBackend = parseBackend;
/* match Not a pure module */
