// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var TemplateFiles = require("./TemplateFiles.res.js");

function validateProjectName(name) {
  if (name.length === 0) {
    console.error("Error: Project name cannot be empty");
    return false;
  } else if (name.startsWith(".") || name.startsWith("_")) {
    console.error("Error: Project name cannot start with '.' or '_'");
    return false;
  } else if (name.includes(" ")) {
    console.error("Error: Project name cannot contain spaces. Use hyphens instead.");
    return false;
  } else if (name.toUpperCase() === name) {
    console.error("Error: Project name should be lowercase");
    return false;
  } else {
    return true;
  }
}

function createProject(projectName) {
  var projectPath = Path.join(process.cwd(), projectName);
  if (Fs.existsSync(projectPath)) {
    console.error("Error: Directory '" + projectName + "' already exists!");
    ((process.exit(1)));
  }
  console.log("Creating project: " + projectName + "...");
  Fs.mkdirSync(projectPath, {
        recursive: true
      });
  Fs.mkdirSync(Path.join(projectPath, "src"), {
        recursive: true
      });
  console.log("  Creating src/IC10.res...");
  Fs.writeFileSync(Path.join(projectPath, "src", "IC10.res"), TemplateFiles.ic10Bindings, "utf8");
  console.log("  Creating src/Example.res...");
  Fs.writeFileSync(Path.join(projectPath, "src", "Example.res"), TemplateFiles.exampleCode, "utf8");
  console.log("  Creating rescript.json...");
  Fs.writeFileSync(Path.join(projectPath, "rescript.json"), TemplateFiles.rescriptConfig(projectName), "utf8");
  console.log("  Creating package.json...");
  Fs.writeFileSync(Path.join(projectPath, "package.json"), TemplateFiles.packageJson(projectName), "utf8");
  console.log("  Creating README.md...");
  Fs.writeFileSync(Path.join(projectPath, "README.md"), TemplateFiles.readme(projectName), "utf8");
  console.log("  Creating .gitignore...");
  Fs.writeFileSync(Path.join(projectPath, ".gitignore"), TemplateFiles.gitignore, "utf8");
  console.log("");
  console.log("✓ Project created successfully!");
  console.log("");
  console.log("Next steps:");
  console.log("  1. cd " + projectName);
  console.log("  2. npm install");
  console.log("  3. npm run dev          (watch mode)");
  console.log("  4. ric10 src/Example.res");
  console.log("");
  console.log("Happy coding! 🚀");
}

var projectName = process.argv[3];

if (projectName !== undefined) {
  if (validateProjectName(projectName)) {
    createProject(projectName);
  }
  
} else {
  console.error("Error: Project name is required");
  console.log("");
  console.log("Usage: ric10 init <project-name>");
  console.log("Example: ric10 init my-ic10-project");
  ((process.exit(1)));
}

exports.validateProjectName = validateProjectName;
exports.createProject = createProject;
/* projectName Not a pure module */
